name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Webapp image
        run: |
          docker build -t ghcr.io/alexthefighter/assignment3-webapp:latest ./webapp
          docker push ghcr.io/alexthefighter/assignment3-webapp:latest

      - name: Tag and push Postgres image
        run: |
          docker pull postgres
          docker tag postgres ghcr.io/alexthefighter/assignment3-db:latest
          docker push ghcr.io/alexthefighter/assignment3-db:latest
