name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Webapp image
        run: |
          IMAGE_NAME=ghcr.io/alexthefighter/assignment3/assignment3-webapp:latest
          docker build -t $IMAGE_NAME ./webapp
          docker push $IMAGE_NAME

      - name: Tag and push Postgres image
        run: |
          docker pull postgres
          IMAGE_NAME=ghcr.io/alexthefighter/assignment3/assignment3-db:latest
          docker tag postgres $IMAGE_NAME
          docker push $IMAGE_NAME
